version: '3'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial1
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web
